name: 'Lint Code'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Create flake8 config
      run: |
        echo "[flake8]
        max-line-length = 79
        extend-ignore = 
            W391, 
            E303,  
            E131, 
            E402,  
            E225,  
            W291,  
            E251,  
            W293,  
            F811,  
            F841, 
            E203,  
            E712   
        per-file-ignores =
            __init__.py:F401,F403
            */views.py:F841
            */models.py:W391
        exclude =
            .git,
            __pycache__,
            build,
            dist,
            migrations
        " > setup.cfg

    - name: Run Python Linter
      run: |
        flake8 .
        echo "Linted all python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install JSHint
      run: npm install jshint --global

    - name: Create JSHint config
      run: |
        echo '{
          "esversion": 8,
          "node": true,
          "asi": true,
          "sub": true
        }' > .jshintrc

    - name: Run JavaScript Linter
      run: |
        find ./server/database -name "*.js" -exec jshint {} +
        echo "Linted all js files successfully"
